// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/common/Banner.vue')['default']
    CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/MenuList.vue')['default']
    MoreText: typeof import('./src/components/common/MoreText.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/PlayerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/PlayerController.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/footer/PlayerSlider.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/PlayerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/footer/PlayerVolumeSlider.vue')['default']
    PlayList: typeof import('./src/components/layout/playList/PlayList.vue')['default']
    PlayListSongItem: typeof import('./src/components/layout/playList/PlayListSongItem.vue')['default']
    SearchPop: typeof import('./src/components/layout/header/SearchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/SearchSuggest.vue')['default']
    SongListItem: typeof import('./src/components/common/SongListItem.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
  }
}

export { }
